import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: ['class'],
  content: [
    // App Router paths
    './src/app/**/*.{ts,tsx,js,jsx,mdx}',
    './src/components/**/*.{ts,tsx,js,jsx}',
    './src/lib/**/*.{ts,tsx,js,jsx}',
    './src/hooks/**/*.{ts,tsx,js,jsx}',
    './src/services/**/*.{ts,tsx,js,jsx}',
    './src/types/**/*.{ts,tsx,js,jsx}',
    // Monorepo packages paths
    '../../packages/**/*.{ts,tsx,js,jsx,mdx}',
    '../../packages/ui/**/*.{ts,tsx,js,jsx}',
    '../../packages/creative-tools/**/*.{ts,tsx,js,jsx}',
    '../../packages/external-games/**/*.{ts,tsx,js,jsx}',
    '../../packages/game-engine/**/*.{ts,tsx,js,jsx}',
    '../../packages/h5p-adapter/**/*.{ts,tsx,js,jsx}',
    '../../packages/quiz-generator/**/*.{ts,tsx,js,jsx}',
    '../../packages/sandbox-connector/**/*.{ts,tsx,js,jsx}',
    '../../packages/schemas/**/*.{ts,tsx,js,jsx}',
    '../../packages/simulation-engine/**/*.{ts,tsx,js,jsx}',
    '../../packages/vr-ar-adapter/**/*.{ts,tsx,js,jsx}',
  ],
  // Safelist para clases dinámicas que se pueden perder en producción
  safelist: [
    // Clases de tamaño dinámico
    'text-xs',
    'text-sm',
    'text-base',
    'text-lg',
    'text-xl',
    'text-2xl',
    'text-3xl',
    // Colores earth dinámicos
    'bg-earth-50',
    'bg-earth-100',
    'bg-earth-200',
    'bg-earth-300',
    'bg-earth-400',
    'bg-earth-500',
    'bg-earth-600',
    'bg-earth-700',
    'bg-earth-800',
    'bg-earth-900',
    'text-earth-50',
    'text-earth-100',
    'text-earth-200',
    'text-earth-300',
    'text-earth-400',
    'text-earth-500',
    'text-earth-600',
    'text-earth-700',
    'text-earth-800',
    'text-earth-900',
    // Clases glass
    'glass',
    'glass-dark',
    // Estados hover/focus
    'hover:bg-earth-700',
    'hover:bg-earth-600',
    'hover:bg-earth-500',
    'focus:ring-earth-500',
    'focus:ring-earth-600',
    // Clases de spacing dinámico
    'p-1',
    'p-2',
    'p-3',
    'p-4',
    'p-5',
    'p-6',
    'p-8',
    'p-10',
    'p-12',
    'm-1',
    'm-2',
    'm-3',
    'm-4',
    'm-5',
    'm-6',
    'm-8',
    'm-10',
    'm-12',
    // Clases de grid/flex dinámicas
    'grid-cols-1',
    'grid-cols-2',
    'grid-cols-3',
    'grid-cols-4',
    'grid-cols-5',
    'grid-cols-6',
    'flex-col',
    'flex-row',
    'flex-wrap',
    'flex-nowrap',
  ],
  theme: {
    extend: {
      colors: {
        earth: {
          50: '#fdf8f6',
          100: '#f2e8e5',
          200: '#eaddd7',
          300: '#e0cec7',
          400: '#d2bab0',
          500: '#bfa094',
          600: '#a18072',
          700: '#977669',
          800: '#846358',
          900: '#43302b',
        },
        glass: {
          white: 'rgba(255, 255, 255, 0.1)',
          dark: 'rgba(0, 0, 0, 0.1)',
        },
      },
      backdropBlur: {
        xs: '2px',
      },
      boxShadow: {
        glass: '0 8px 32px 0 rgba(31, 38, 135, 0.37)',
        'glass-inset': 'inset 0 1px 0 0 rgba(255, 255, 255, 0.05)',
      },
    },
  },
  plugins: [],
};
export default config;
